---
- hosts: Local
  user: root
  become: True
  gather_facts: no
  tasks:
    - name: displaying msg
      debug: msg="My name is Hello"

    - name: installing ntpd
      yum: name='ntp' state=present
